// Generated by gencpp from file h3_msgs/Joint.msg
// DO NOT EDIT!


#ifndef H3_MSGS_MESSAGE_JOINT_H
#define H3_MSGS_MESSAGE_JOINT_H

#include <ros/service_traits.h>


#include <h3_msgs/JointRequest.h>
#include <h3_msgs/JointResponse.h>


namespace h3_msgs
{

struct Joint
{

typedef JointRequest Request;
typedef JointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Joint
} // namespace h3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h3_msgs::Joint > {
  static const char* value()
  {
    return "98e232ffcfd0fe1cbfc298199f488310";
  }

  static const char* value(const ::h3_msgs::Joint&) { return value(); }
};

template<>
struct DataType< ::h3_msgs::Joint > {
  static const char* value()
  {
    return "h3_msgs/Joint";
  }

  static const char* value(const ::h3_msgs::Joint&) { return value(); }
};


// service_traits::MD5Sum< ::h3_msgs::JointRequest> should match
// service_traits::MD5Sum< ::h3_msgs::Joint >
template<>
struct MD5Sum< ::h3_msgs::JointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h3_msgs::Joint >::value();
  }
  static const char* value(const ::h3_msgs::JointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h3_msgs::JointRequest> should match
// service_traits::DataType< ::h3_msgs::Joint >
template<>
struct DataType< ::h3_msgs::JointRequest>
{
  static const char* value()
  {
    return DataType< ::h3_msgs::Joint >::value();
  }
  static const char* value(const ::h3_msgs::JointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h3_msgs::JointResponse> should match
// service_traits::MD5Sum< ::h3_msgs::Joint >
template<>
struct MD5Sum< ::h3_msgs::JointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h3_msgs::Joint >::value();
  }
  static const char* value(const ::h3_msgs::JointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h3_msgs::JointResponse> should match
// service_traits::DataType< ::h3_msgs::Joint >
template<>
struct DataType< ::h3_msgs::JointResponse>
{
  static const char* value()
  {
    return DataType< ::h3_msgs::Joint >::value();
  }
  static const char* value(const ::h3_msgs::JointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H3_MSGS_MESSAGE_JOINT_H
