// Generated by gencpp from file h3_msgs/TriggerOutput.msg
// DO NOT EDIT!


#ifndef H3_MSGS_MESSAGE_TRIGGEROUTPUT_H
#define H3_MSGS_MESSAGE_TRIGGEROUTPUT_H

#include <ros/service_traits.h>


#include <h3_msgs/TriggerOutputRequest.h>
#include <h3_msgs/TriggerOutputResponse.h>


namespace h3_msgs
{

struct TriggerOutput
{

typedef TriggerOutputRequest Request;
typedef TriggerOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerOutput
} // namespace h3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h3_msgs::TriggerOutput > {
  static const char* value()
  {
    return "12bdd23eb6cb70720a3a754d3f099d35";
  }

  static const char* value(const ::h3_msgs::TriggerOutput&) { return value(); }
};

template<>
struct DataType< ::h3_msgs::TriggerOutput > {
  static const char* value()
  {
    return "h3_msgs/TriggerOutput";
  }

  static const char* value(const ::h3_msgs::TriggerOutput&) { return value(); }
};


// service_traits::MD5Sum< ::h3_msgs::TriggerOutputRequest> should match
// service_traits::MD5Sum< ::h3_msgs::TriggerOutput >
template<>
struct MD5Sum< ::h3_msgs::TriggerOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h3_msgs::TriggerOutput >::value();
  }
  static const char* value(const ::h3_msgs::TriggerOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h3_msgs::TriggerOutputRequest> should match
// service_traits::DataType< ::h3_msgs::TriggerOutput >
template<>
struct DataType< ::h3_msgs::TriggerOutputRequest>
{
  static const char* value()
  {
    return DataType< ::h3_msgs::TriggerOutput >::value();
  }
  static const char* value(const ::h3_msgs::TriggerOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h3_msgs::TriggerOutputResponse> should match
// service_traits::MD5Sum< ::h3_msgs::TriggerOutput >
template<>
struct MD5Sum< ::h3_msgs::TriggerOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h3_msgs::TriggerOutput >::value();
  }
  static const char* value(const ::h3_msgs::TriggerOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h3_msgs::TriggerOutputResponse> should match
// service_traits::DataType< ::h3_msgs::TriggerOutput >
template<>
struct DataType< ::h3_msgs::TriggerOutputResponse>
{
  static const char* value()
  {
    return DataType< ::h3_msgs::TriggerOutput >::value();
  }
  static const char* value(const ::h3_msgs::TriggerOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H3_MSGS_MESSAGE_TRIGGEROUTPUT_H
